name: Deploy

on: 
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#     - run: npm install && npm run build
#     - run: |
#         rm -rf ../build
#         mkdir ../build
#         cp -TR ./build ../build
#         tar -cvf deploy.tar ../build/
    
#     - name: Copy repository contents via scp
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         port: ${{ secrets.PORT }}
#         source: "deploy.tar"
#         target: "onlineEditor/client"
#         timeout: 10m
#         command_timeout: 20m
        
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "onlineEditor/client"
        timeout: 10m
        command_timeout: 20m

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ~/onlineEditor && nvm use default && npm install
          cd ~/onlineEditor/client && npm install && npm run build && next export -o ./build
          pm2 restart code_editor
